# Generated by Django 5.2.3 on 2025-06-30 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "community_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("restricted", "Restricted"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("member_count", models.PositiveIntegerField(default=1)),
                ("poll_count", models.PositiveIntegerField(default=0)),
                ("requires_aura_to_join", models.PositiveIntegerField(default=0)),
                ("requires_aura_to_post", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_communities",
                        to="profile.pseudonymousprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Communities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityMembership",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                            ("creator", "Creator"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("banned", "Banned"),
                            ("left", "Left"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="communities.community",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_memberships",
                        to="profile.pseudonymousprofile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["community_type", "-created_at"],
                name="communities_communi_8463e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["-member_count"], name="communities_member__b80a75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="communities_is_acti_862196_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="communitymembership",
            index=models.Index(
                fields=["community", "status"], name="communities_communi_8af3bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymembership",
            index=models.Index(
                fields=["profile", "status"], name="communities_profile_9487a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymembership",
            index=models.Index(
                fields=["community", "role"], name="communities_communi_5808bc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communitymembership",
            unique_together={("community", "profile")},
        ),
    ]
