# Generated by Django 5.2.3 on 2025-07-01 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_category_options_remove_category_allows_gifs_and_more"),
        ("communities", "0001_initial"),
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Community avatar image",
                null=True,
                upload_to="community_avatars/",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Community banner image",
                null=True,
                upload_to="community_banners/",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communities",
                to="common.category",
            ),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["category", "-created_at"],
                name="communities_categor_72bac6_idx",
            ),
        ),
    ]
