# Generated by Django 5.2.3 on 2025-07-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0003_community_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique URL-friendly identifier for the community",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
