# Generated by Django 5.2.3 on 2025-07-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0004_community_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitymembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("moderator", "Moderator"),
                    ("recruiter", "Recruiter"),
                    ("creator", "Creator"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
