# Generated by Django 5.1.4 on 2025-05-18 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Category"),
                            ("feed", "Feed Type"),
                            ("system", "System Category"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("icon_color", models.CharField(blank=True, max_length=20)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("character_limit", models.PositiveIntegerField(default=2000)),
                ("allows_images", models.BooleanField(default=True)),
                ("allows_gifs", models.BooleanField(default=True)),
                ("allows_videos", models.BooleanField(default=True)),
                ("allows_links", models.BooleanField(default=True)),
                ("allows_polls", models.BooleanField(default=True)),
                ("allows_location", models.BooleanField(default=True)),
                ("max_images", models.PositiveSmallIntegerField(default=4)),
                (
                    "max_video_duration",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("allows_tags", models.BooleanField(default=True)),
                ("max_tags", models.PositiveSmallIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("usage_count", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="common_tag_name_3a4898_idx"),
                    models.Index(
                        fields=["usage_count"], name="common_tag_usage_c_0f4346_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("url", models.URLField(max_length=2000)),
                ("display_text", models.CharField(blank=True, max_length=2000)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="common_link_content_04f2c5_idx",
                    ),
                    models.Index(
                        fields=["domain"], name="common_link_domain_9ffb4e_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="common_link_created_2553a1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("file", models.FileField(upload_to="media/%Y/%m/%d/")),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True, null=True, upload_to="media/thumbnails/%Y/%m/%d/"
                    ),
                ),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("video_codec", models.CharField(blank=True, max_length=50, null=True)),
                ("audio_codec", models.CharField(blank=True, max_length=50, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Media",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "media_type"],
                        name="common_medi_content_de36e6_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="common_medi_created_e79ed4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("icon_color", models.CharField(blank=True, max_length=20)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="common.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sub Categories",
                "ordering": ["category", "display_order", "name"],
                "unique_together": {("name", "category")},
            },
        ),
        migrations.CreateModel(
            name="TaggedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="common.tag",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="common_tagg_content_d5c4f4_idx",
                    )
                ],
                "unique_together": {("tag", "content_type", "object_id")},
            },
        ),
    ]
