# Generated by Django 5.2.3 on 2025-07-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="allows_gifs",
        ),
        migrations.RemoveField(
            model_name="category",
            name="allows_images",
        ),
        migrations.RemoveField(
            model_name="category",
            name="allows_links",
        ),
        migrations.RemoveField(
            model_name="category",
            name="allows_location",
        ),
        migrations.RemoveField(
            model_name="category",
            name="allows_polls",
        ),
        migrations.RemoveField(
            model_name="category",
            name="allows_tags",
        ),
        migrations.RemoveField(
            model_name="category",
            name="allows_videos",
        ),
        migrations.RemoveField(
            model_name="category",
            name="character_limit",
        ),
        migrations.RemoveField(
            model_name="category",
            name="display_order",
        ),
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="category",
            name="icon_color",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="category",
            name="max_images",
        ),
        migrations.RemoveField(
            model_name="category",
            name="max_tags",
        ),
        migrations.RemoveField(
            model_name="category",
            name="max_video_duration",
        ),
        migrations.RemoveField(
            model_name="category",
            name="requires_approval",
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
    ]
