# Generated by Django 5.1.4 on 2025-05-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_uploadedimage_alter_media_media_type_genericcomment_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenericComment",
        ),
    ]
