# Generated by Django 5.2.3 on 2025-07-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_category_options_remove_category_allows_gifs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
