# Generated by Django 5.2.3 on 2025-07-21 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_tag_description"),
        ("communities", "0005_alter_communitymembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="taggeditem",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_items",
                to="communities.community",
            ),
        ),
    ]
