# Generated by Django 5.1.4 on 2025-05-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_delete_genericcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[("standard", "Standard Category"), ("feed", "Feed Type")],
                default="standard",
                max_length=20,
            ),
        ),
    ]
