# Generated by Django 5.1.4 on 2025-05-28 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_category_category_type"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blocker_object_id", models.PositiveIntegerField()),
                ("blocked_object_id", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment"),
                            ("inappropriate", "Inappropriate Content"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_received",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "blocker_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_made",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["blocker_content_type", "blocker_object_id"],
                        name="common_bloc_blocker_92235d_idx",
                    ),
                    models.Index(
                        fields=["blocked_content_type", "blocked_object_id"],
                        name="common_bloc_blocked_fe181c_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="common_bloc_created_705289_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "blocker_content_type",
                        "blocker_object_id",
                        "blocked_content_type",
                        "blocked_object_id",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower_object_id", models.PositiveIntegerField()),
                ("followee_object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notify_on_posts", models.BooleanField(default=True)),
                (
                    "followee_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followee_follows",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "follower_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_follows",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=[
                            "followee_content_type",
                            "followee_object_id",
                            "is_active",
                        ],
                        name="common_foll_followe_ddb93b_idx",
                    ),
                    models.Index(
                        fields=[
                            "follower_content_type",
                            "follower_object_id",
                            "is_active",
                        ],
                        name="common_foll_followe_60d0de_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="common_foll_created_922d32_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "follower_content_type",
                        "follower_object_id",
                        "followee_content_type",
                        "followee_object_id",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="FollowRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester_object_id", models.PositiveIntegerField()),
                ("target_object_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requester_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_requests_made",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_requests_received",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_content_type", "target_object_id", "status"],
                        name="common_foll_target__9a3ddb_idx",
                    ),
                    models.Index(
                        fields=[
                            "requester_content_type",
                            "requester_object_id",
                            "status",
                        ],
                        name="common_foll_request_07de4d_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="common_foll_created_4c3269_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "requester_content_type",
                        "requester_object_id",
                        "target_content_type",
                        "target_object_id",
                    )
                },
            },
        ),
    ]
