# Generated by Django 5.1.4 on 2025-05-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_block_follow_followrequest"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("profiles", "0010_remove_pseudonymousprofile_follower_count_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reaction",
            name="unique_member_reaction_per_object",
        ),
        migrations.RemoveIndex(
            model_name="reaction",
            name="common_reac_member__5336b6_idx",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="member",
        ),
        migrations.AddField(
            model_name="reaction",
            name="public_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="profiles.publicprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["public_profile", "-created_at"],
                name="common_reac_public__059c1a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("public_profile", "content_type", "object_id", "reaction_type"),
                name="unique_public_profile_reaction_per_object",
            ),
        ),
    ]
