# Generated by Django 5.1.4 on 2025-05-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_bookmarkfolder_bookmark_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookmark",
            name="unique_bookmark_per_user_per_content",
        ),
        migrations.RemoveConstraint(
            model_name="bookmarkfolder",
            name="unique_folder_name_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="reaction",
            name="unique_public_profile_reaction_per_object",
        ),
        migrations.RemoveIndex(
            model_name="bookmark",
            name="common_book_public__b4c827_idx",
        ),
        migrations.RemoveIndex(
            model_name="bookmark",
            name="common_book_public__124b12_idx",
        ),
        migrations.RemoveIndex(
            model_name="bookmarkfolder",
            name="common_book_public__88dfa1_idx",
        ),
        migrations.RemoveIndex(
            model_name="bookmarkfolder",
            name="common_book_public__025c59_idx",
        ),
        migrations.RemoveIndex(
            model_name="reaction",
            name="common_reac_public__059c1a_idx",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="public_profile",
        ),
        migrations.RemoveField(
            model_name="bookmarkfolder",
            name="public_profile",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="public_profile",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="profile_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookmark",
            name="profile_type",
            field=models.CharField(
                choices=[
                    ("professional", "Professional"),
                    ("public", "Public"),
                    ("pseudonymous", "Pseudonymous"),
                    ("anonymous", "Anonymous"),
                ],
                default="public",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookmarkfolder",
            name="profile_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookmarkfolder",
            name="profile_type",
            field=models.CharField(
                choices=[
                    ("professional", "Professional"),
                    ("public", "Public"),
                    ("pseudonymous", "Pseudonymous"),
                    ("anonymous", "Anonymous"),
                ],
                default="public",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reaction",
            name="profile_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reaction",
            name="profile_type",
            field=models.CharField(
                choices=[
                    ("professional", "Professional"),
                    ("public", "Public"),
                    ("pseudonymous", "Pseudonymous"),
                    ("anonymous", "Anonymous"),
                ],
                default="public",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["profile_type", "profile_id", "-created_at"],
                name="common_book_profile_f96403_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["profile_type", "profile_id", "folder"],
                name="common_book_profile_c8d1b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmarkfolder",
            index=models.Index(
                fields=["profile_type", "profile_id", "name"],
                name="common_book_profile_5f7f55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmarkfolder",
            index=models.Index(
                fields=["profile_type", "profile_id", "-created_at"],
                name="common_book_profile_df610b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["profile_type", "profile_id", "-created_at"],
                name="common_reac_profile_92ad81_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                fields=("profile_type", "profile_id", "content_type", "object_id"),
                name="unique_bookmark_per_profile_per_content",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmarkfolder",
            constraint=models.UniqueConstraint(
                fields=("profile_type", "profile_id", "name"),
                name="unique_folder_name_per_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=(
                    "profile_type",
                    "profile_id",
                    "content_type",
                    "object_id",
                    "reaction_type",
                ),
                name="unique_profile_reaction_per_object",
            ),
        ),
    ]
