# Generated by Django 5.1.4 on 2025-06-06 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "common",
            "0008_remove_bookmark_unique_bookmark_per_user_per_content_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Impression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "profile_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("professional", "Professional"),
                            ("public", "Public"),
                            ("pseudonymous", "Pseudonymous"),
                            ("anonymous", "Anonymous"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("profile_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "user_agent_hash",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("referrer", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "created_at"],
                        name="common_impr_content_4b4422_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="common_impr_ip_addr_f69c1b_idx",
                    ),
                    models.Index(
                        fields=["profile_type", "profile_id", "created_at"],
                        name="common_impr_profile_7d6055_idx",
                    ),
                    models.Index(
                        fields=["session_key", "created_at"],
                        name="common_impr_session_0fe289_idx",
                    ),
                ],
            },
        ),
    ]
