# Generated by Django 5.1.4 on 2025-06-11 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_impression"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("public", "Public"),
                            ("pseudonymous", "Pseudonymous"),
                            ("anonymous", "Anonymous"),
                        ],
                        max_length=20,
                    ),
                ),
                ("profile_id", models.PositiveIntegerField()),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("reddit", "Reddit"),
                            ("email", "Email"),
                            ("link", "Direct Link"),
                            ("embed", "Embed Code"),
                            ("native", "Native Share"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-shared_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="common_shar_content_618509_idx",
                    ),
                    models.Index(
                        fields=["profile_type", "profile_id"],
                        name="common_shar_profile_0f172b_idx",
                    ),
                    models.Index(
                        fields=["platform", "shared_at"],
                        name="common_shar_platfor_9fd53c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "content_type",
                            "object_id",
                            "profile_type",
                            "profile_id",
                            "platform",
                        ),
                        name="unique_share_per_profile_platform",
                    )
                ],
            },
        ),
    ]
