# Generated by Django 5.1.4 on 2025-06-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_share"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="share",
            name="unique_share_per_profile_platform",
        ),
        migrations.AlterField(
            model_name="share",
            name="profile_type",
            field=models.CharField(
                choices=[
                    ("professional", "Professional"),
                    ("public", "Public"),
                    ("pseudonymous", "Pseudonymous"),
                    ("anonymous", "Anonymous"),
                    ("unauthenticated", "Unauthenticated"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="share",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "profile_type__in",
                        ["professional", "public", "pseudonymous", "anonymous"],
                    )
                ),
                fields=(
                    "content_type",
                    "object_id",
                    "profile_type",
                    "profile_id",
                    "platform",
                ),
                name="unique_share_per_authenticated_profile_platform",
            ),
        ),
        migrations.AddConstraint(
            model_name="share",
            constraint=models.UniqueConstraint(
                condition=models.Q(("profile_type", "unauthenticated")),
                fields=("content_type", "object_id", "ip_address", "platform"),
                name="unique_share_per_unauthenticated_user_platform",
            ),
        ),
    ]
