# Generated by Django 5.1.4 on 2025-06-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_remove_share_unique_share_per_profile_platform_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="follow",
            name="followee_content_type",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="follower_content_type",
        ),
        migrations.AlterUniqueTogether(
            name="followrequest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="followrequest",
            name="requester_content_type",
        ),
        migrations.RemoveField(
            model_name="followrequest",
            name="target_content_type",
        ),
        migrations.DeleteModel(
            name="Block",
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
        migrations.DeleteModel(
            name="FollowRequest",
        ),
    ]
