# Generated by Django 5.1.4 on 2025-06-13 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_alter_follow_unique_together_and_more"),
        ("profiles", "0018_pseudonymousprofile_show_joined_communities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment"),
                            ("inappropriate", "Inappropriate Content"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_received",
                        to="profiles.publicprofile",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_made",
                        to="profiles.publicprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["blocker"], name="common_bloc_blocker_3b86c2_idx"
                    ),
                    models.Index(
                        fields=["blocked"], name="common_bloc_blocked_b382c6_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="common_bloc_created_705289_idx"
                    ),
                ],
                "unique_together": {("blocker", "blocked")},
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notify_on_posts", models.BooleanField(default=True)),
                (
                    "followee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_relationships",
                        to="profiles.publicprofile",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_relationships",
                        to="profiles.publicprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["followee", "is_active"],
                        name="common_foll_followe_6d79d5_idx",
                    ),
                    models.Index(
                        fields=["follower", "is_active"],
                        name="common_foll_followe_67f892_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="common_foll_created_922d32_idx"
                    ),
                ],
                "unique_together": {("follower", "followee")},
            },
        ),
        migrations.CreateModel(
            name="FollowRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_requests_made",
                        to="profiles.publicprofile",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_requests_received",
                        to="profiles.publicprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target", "status"],
                        name="common_foll_target__9a423f_idx",
                    ),
                    models.Index(
                        fields=["requester", "status"],
                        name="common_foll_request_70ae4f_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="common_foll_created_4c3269_idx"
                    ),
                ],
                "unique_together": {("requester", "target")},
            },
        ),
    ]
