# Generated by Django 5.1.4 on 2025-06-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_block_follow_followrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impression",
            name="profile_type",
            field=models.CharField(
                blank=True,
                choices=[("public", "Public"), ("anonymous", "Anonymous")],
                max_length=20,
                null=True,
            ),
        ),
    ]
