# Generated by Django 5.1.4 on 2025-06-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_alter_impression_profile_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="impression",
            name="country_code",
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
    ]
