# Generated by Django 5.1.4 on 2025-06-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_impression_country_code"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="impression",
            name="common_impr_profile_7d6055_idx",
        ),
        migrations.RemoveField(
            model_name="impression",
            name="profile_type",
        ),
        migrations.AddIndex(
            model_name="impression",
            index=models.Index(
                fields=["profile_id", "created_at"],
                name="common_impr_profile_85e88a_idx",
            ),
        ),
    ]
