# Generated by Django 5.1.4 on 2025-06-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0016_remove_impression_common_impr_profile_7d6055_idx_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="profile_id",
            field=models.BigIntegerField(help_text="ID of the public profile"),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="profile_type",
            field=models.CharField(
                choices=[("public", "Public")],
                default="public",
                help_text="Profile type - currently only 'public' is supported",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookmarkfolder",
            name="profile_id",
            field=models.BigIntegerField(help_text="ID of the public profile"),
        ),
        migrations.AlterField(
            model_name="bookmarkfolder",
            name="profile_type",
            field=models.CharField(
                choices=[("public", "Public")],
                default="public",
                help_text="Profile type - currently only 'public' is supported",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["profile_id", "-created_at"],
                name="common_book_profile_783f00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["profile_id", "folder"], name="common_book_profile_a19b72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmarkfolder",
            index=models.Index(
                fields=["profile_id", "-created_at"],
                name="common_book_profile_9fadc7_idx",
            ),
        ),
    ]
