services:
  # nginx-proxy with basic SSL support for staging
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - static_volume:/usr/share/nginx/html/static:ro
      - media_volume:/usr/share/nginx/html/media:ro
    environment:
      - DEFAULT_HOST=${STAGING_DOMAIN}
    restart: unless-stopped
    networks:
      - proxy-network

  # ACME companion for automatic SSL certificates (staging)
  acme-companion:
    image: nginxproxy/acme-companion:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${ACME_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory  # Staging CA
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    networks:
      - proxy-network

  web:
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 early_access_api.asgi:application"
    env_file:
      - .env.staging
    environment:
      - DEBUG=False
      - USE_REDIS=${USE_REDIS:-true}
      - VIRTUAL_HOST=${STAGING_DOMAIN}
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=${STAGING_DOMAIN}
      - LETSENCRYPT_EMAIL=${ACME_EMAIL}
      - DJANGO_SETTINGS_MODULE=early_access_api.settings.staging
    restart: unless-stopped
    # Remove port exposure for staging (only accessible via nginx-proxy)

  celery:
    env_file:
      - .env.staging
    environment:
      - USE_REDIS=${USE_REDIS:-true}
      - DJANGO_SETTINGS_MODULE=early_access_api.settings.staging

  celery-beat:
    env_file:
      - .env.staging
    environment:
      - USE_REDIS=${USE_REDIS:-true}
      - DJANGO_SETTINGS_MODULE=early_access_api.settings.staging

volumes:
  nginx-certs:
  nginx-vhosts:
  nginx-html:
  acme: