# Generated by Django 5.1.4 on 2025-06-15 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0006_alter_genericcomment_profile_type_and_more"),
        ("connect_notifications", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("posts", "0015_remove_post_post_has_exactly_one_profile_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("share", "Share"),
                    ("bookmark", "Bookmark"),
                    ("view", "View"),
                    ("reply", "Reply"),
                    ("follow", "Follow"),
                    ("mention", "Mention"),
                    ("followed_user_post", "Followed User Post"),
                    ("followed_post_update", "Followed Post Update"),
                    ("followed_comment_reply", "Followed Comment Reply"),
                    ("like_milestone", "Like Milestone"),
                    ("share_milestone", "Share Milestone"),
                    ("view_milestone", "View Milestone"),
                    ("bookmark_milestone", "Bookmark Milestone"),
                    ("follower_milestone", "Follower Milestone"),
                    ("verification", "Verification"),
                    ("welcome", "Welcome"),
                    ("system", "System"),
                    ("custom", "Custom"),
                ],
                default="system",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("share", "Share"),
                    ("bookmark", "Bookmark"),
                    ("view", "View"),
                    ("reply", "Reply"),
                    ("follow", "Follow"),
                    ("mention", "Mention"),
                    ("followed_user_post", "Followed User Post"),
                    ("followed_post_update", "Followed Post Update"),
                    ("followed_comment_reply", "Followed Comment Reply"),
                    ("like_milestone", "Like Milestone"),
                    ("share_milestone", "Share Milestone"),
                    ("view_milestone", "View Milestone"),
                    ("bookmark_milestone", "Bookmark Milestone"),
                    ("follower_milestone", "Follower Milestone"),
                    ("verification", "Verification"),
                    ("welcome", "Welcome"),
                    ("system", "System"),
                    ("custom", "Custom"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CommentFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower_object_id", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "auto_followed",
                    models.BooleanField(
                        default=True,
                        help_text="True if auto-followed by interaction, False if manually followed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="comments.genericcomment",
                    ),
                ),
                (
                    "follower_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_follows",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["comment", "is_active"],
                        name="connect_not_comment_7b0a6e_idx",
                    ),
                    models.Index(
                        fields=["follower_content_type", "follower_object_id"],
                        name="connect_not_followe_0da413_idx",
                    ),
                ],
                "unique_together": {
                    ("follower_content_type", "follower_object_id", "comment")
                },
            },
        ),
        migrations.CreateModel(
            name="PostFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower_object_id", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "auto_followed",
                    models.BooleanField(
                        default=True,
                        help_text="True if auto-followed by interaction, False if manually followed",
                    ),
                ),
                ("notify_on_comments", models.BooleanField(default=True)),
                ("notify_on_likes", models.BooleanField(default=False)),
                ("notify_on_shares", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "follower_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_follows",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["post", "is_active"],
                        name="connect_not_post_id_44f904_idx",
                    ),
                    models.Index(
                        fields=["follower_content_type", "follower_object_id"],
                        name="connect_not_followe_e0eb98_idx",
                    ),
                ],
                "unique_together": {
                    ("follower_content_type", "follower_object_id", "post")
                },
            },
        ),
    ]
