# Generated by Django 5.1.4 on 2025-06-16 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect_notifications", "0002_alter_notification_notification_type_and_more"),
        (
            "profiles",
            "0020_remove_publicprofile_profiles_pu_user_na_1429d7_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FCMDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        max_length=10,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="connect_not_is_clic_754a73_idx",
        ),
        migrations.RemoveField(
            model_name="postfollow",
            name="notify_on_comments",
        ),
        migrations.RemoveField(
            model_name="postfollow",
            name="notify_on_likes",
        ),
        migrations.RemoveField(
            model_name="postfollow",
            name="notify_on_shares",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("reply", "Reply"),
                    ("follow", "Follow"),
                    ("mention", "Mention"),
                    ("followed_user_post", "Followed User Post"),
                    ("followed_post_comment", "Followed Post Comment"),
                    ("followed_comment_reply", "Followed Comment Reply"),
                    ("like_milestone", "Like Milestone"),
                    ("share_milestone", "Share Milestone"),
                    ("bookmark_milestone", "Bookmark Milestone"),
                    ("impression_milestone", "Impression Milestone"),
                    ("follower_milestone", "Follower Milestone"),
                    ("verification", "Verification"),
                    ("welcome", "Welcome"),
                    ("system", "System"),
                ],
                default="system",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("reply", "Reply"),
                    ("follow", "Follow"),
                    ("mention", "Mention"),
                    ("followed_user_post", "Followed User Post"),
                    ("followed_post_comment", "Followed Post Comment"),
                    ("followed_comment_reply", "Followed Comment Reply"),
                    ("like_milestone", "Like Milestone"),
                    ("share_milestone", "Share Milestone"),
                    ("bookmark_milestone", "Bookmark Milestone"),
                    ("impression_milestone", "Impression Milestone"),
                    ("follower_milestone", "Follower Milestone"),
                    ("verification", "Verification"),
                    ("welcome", "Welcome"),
                    ("system", "System"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="push_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fcmdevice",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fcm_devices",
                to="profiles.publicprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="fcmdevice",
            index=models.Index(
                fields=["profile", "active"], name="connect_not_profile_7cd2f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fcmdevice",
            index=models.Index(fields=["token"], name="connect_not_token_5f7416_idx"),
        ),
    ]
