# Generated by Django 5.1.4 on 2025-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect_notifications", "0003_fcmdevice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("reply", "Reply"),
                    ("follow", "Follow"),
                    ("mention", "Mention"),
                    ("followed_user_post", "Followed User Post"),
                    ("followed_post_comment", "Followed Post Comment"),
                    ("followed_comment_reply", "Followed Comment Reply"),
                    ("like_milestone", "Like Milestone"),
                    ("share_milestone", "Share Milestone"),
                    ("bookmark_milestone", "Bookmark Milestone"),
                    ("impression_milestone", "Impression Milestone"),
                    ("follower_milestone", "Follower Milestone"),
                    ("replies_milestone", "Replies Milestone"),
                    ("verification", "Verification"),
                    ("welcome", "Welcome"),
                    ("system", "System"),
                ],
                default="system",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("reply", "Reply"),
                    ("follow", "Follow"),
                    ("mention", "Mention"),
                    ("followed_user_post", "Followed User Post"),
                    ("followed_post_comment", "Followed Post Comment"),
                    ("followed_comment_reply", "Followed Comment Reply"),
                    ("like_milestone", "Like Milestone"),
                    ("share_milestone", "Share Milestone"),
                    ("bookmark_milestone", "Bookmark Milestone"),
                    ("impression_milestone", "Impression Milestone"),
                    ("follower_milestone", "Follower Milestone"),
                    ("replies_milestone", "Replies Milestone"),
                    ("verification", "Verification"),
                    ("welcome", "Welcome"),
                    ("system", "System"),
                ],
                max_length=50,
            ),
        ),
    ]
