# Generated by Django 5.2.3 on 2025-07-19 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communities", "0005_alter_communitymembership_role"),
        ("profile", "0003_pseudonymousprofile_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "main_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="articles/images/"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Markdown content of the article",
                        null=True,
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to the article",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="profile.pseudonymousprofile",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="communities.community",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["community", "is_published"],
                        name="articles_ar_communi_d15d4f_idx",
                    ),
                    models.Index(
                        fields=["author", "created_at"],
                        name="articles_ar_author__117e9b_idx",
                    ),
                ],
            },
        ),
    ]
