# Generated by Django 5.2.3 on 2025-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("communities", "0005_alter_communitymembership_role"),
        ("profile", "0003_pseudonymousprofile_about"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="articles_ar_author__117e9b_idx",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="author",
            new_name="creator",
        ),
        migrations.AddField(
            model_name="article",
            name="author_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the article author",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="dislikes_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="article",
            name="impressions_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="article",
            name="likes_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="article",
            name="shares_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["creator", "created_at"], name="articles_ar_creator_f0e70a_idx"
            ),
        ),
    ]
