# Generated by Django 5.2.3 on 2025-08-11 14:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communities", "0005_alter_communitymembership_role"),
        ("profile", "0004_pseudonymousprofile_total_aura"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_activity_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="communities.community",
                    ),
                ),
                (
                    "participant_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats_as_participant_1",
                        to="profile.pseudonymousprofile",
                    ),
                ),
                (
                    "participant_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats_as_participant_2",
                        to="profile.pseudonymousprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity_at"],
                "unique_together": {("participant_1", "participant_2")},
            },
        ),
        migrations.CreateModel(
            name="TimelineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("audio", "Audio Message"),
                            ("voice_call", "Voice Call"),
                            ("video_call", "Video Call"),
                            ("service", "Service Item"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="chat_files/"),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("call_duration", models.IntegerField(blank=True, null=True)),
                ("call_status", models.CharField(blank=True, max_length=15, null=True)),
                ("is_delivered", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_items",
                        to="chats.chat",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_items",
                        to="profile.pseudonymousprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_muted", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="chats.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.pseudonymousprofile",
                    ),
                ),
                (
                    "last_read_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_by_participants",
                        to="chats.timelineitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("chat", "user")},
            },
        ),
    ]
