# Generated by Django 5.2.3 on 2025-08-11 20:53

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
        ("communities", "0005_alter_communitymembership_role"),
        ("profile", "0005_pseudonymousprofile_is_online_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineitem",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_items",
                to="communities.community",
            ),
        ),
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("dm", "Direct Message"),
                            ("live_chat", "Live Chat"),
                            ("audio_call", "Audio Call"),
                            ("video_call", "Video Call"),
                            ("custom", "Custom Service"),
                        ],
                        help_text="Type of service offered",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the service", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what this service provides"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in credits for this service",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Duration in minutes (for timed services like calls)",
                    ),
                ),
                (
                    "is_duration_based",
                    models.BooleanField(
                        default=False, help_text="Whether this service has a time limit"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("draft", "Draft"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether users can currently purchase this service",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_purchases", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        help_text="The community this service belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="communities.community",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="The moderator who created this service",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_services",
                        to="profile.pseudonymousprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("creator", "community", "service_type")},
            },
        ),
        migrations.CreateModel(
            name="ServiceAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="File attachment for the service",
                        upload_to="service_attachments/",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for the attachment",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description for the attachment"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which attachments are displayed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chats.serviceitem",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="timelineitem",
            name="service_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_items",
                to="chats.serviceitem",
            ),
        ),
    ]
