# Generated by Django 5.2.3 on 2025-08-12 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_timelineitem_community_serviceitem_serviceattachment_and_more"),
        ("profile", "0005_pseudonymousprofile_is_online_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who uploaded this attachment (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_attachments",
                to="profile.pseudonymousprofile",
            ),
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="attachments_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether users need to attach files (e.g., images, documents) when purchasing this service",
            ),
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="is_broadcasted",
            field=models.BooleanField(
                default=False,
                help_text="Whether this service has been broadcasted to the community",
            ),
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="Preview image for the service",
                null=True,
                upload_to="service_previews/",
            ),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("dm", "Direct Message"),
                    ("live_chat", "Live Chat"),
                    ("audio_call", "Audio Call"),
                    ("video_call", "Video Call"),
                    ("group_chat", "Group Chat"),
                    ("group_audio_call", "Group Audio Call"),
                    ("group_video_call", "Group Video Call"),
                    ("custom", "Custom Service"),
                ],
                help_text="Type of service offered",
                max_length=20,
            ),
        ),
    ]
