# Generated by Django 5.2.3 on 2025-08-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_serviceattachment_uploaded_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceitem",
            name="max_messages_a_day",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of messages a moderator wants to accept per day",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="attachments_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether users need to attach files (e.g., images, documents) when using this service. Ex: Resume review, photo review, etc.",
            ),
        ),
    ]
