# Generated by Django 5.2.3 on 2025-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_serviceitem_max_messages_a_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceitem",
            name="reply_time",
            field=models.PositiveIntegerField(
                default=1, help_text="Expected reply time in days for this service"
            ),
        ),
    ]
