# Generated by Django 5.2.3 on 2025-08-15 19:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_serviceitem_reply_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineitem",
            name="impressions_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="timelineitem",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price in credits for this service",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("dm", "Direct Message"),
                    ("live_chat", "Live Chat"),
                    ("audio_call", "Audio Call"),
                    ("video_call", "Video Call"),
                    ("custom", "Custom Service"),
                    ("group_chat", "Group Chat"),
                    ("group_audio_call", "Group Audio Call"),
                    ("group_video_call", "Group Video Call"),
                ],
                help_text="Type of service offered",
                max_length=20,
            ),
        ),
    ]
