# Generated by Django 5.2.3 on 2025-08-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_timelineitem_impressions_count_and_more"),
        ("communities", "0005_alter_communitymembership_role"),
        ("profile", "0008_pseudonymousprofile_headline_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="serviceitem",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="serviceitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "service_type__in",
                        ["dm", "live_chat", "audio_call", "video_call"],
                    )
                ),
                fields=("creator", "community", "service_type"),
                name="unique_personal_service_per_creator_community",
            ),
        ),
    ]
