# Generated by Django 5.2.3 on 2025-08-15 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0007_alter_serviceitem_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timelineitem",
            name="file",
        ),
        migrations.RemoveField(
            model_name="timelineitem",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="timelineitem",
            name="file_size",
        ),
        migrations.CreateModel(
            name="TimelineItemAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="File attachment for the timeline item",
                        upload_to="timeline_attachments/",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "timeline_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chats.timelineitem",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
            },
        ),
    ]
