# Generated by Django 5.2.3 on 2025-08-16 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0008_remove_timelineitem_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineitem",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="chats.timelineitem",
            ),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("dm", "Direct Message"),
                    ("live_chat", "Live Chat"),
                    ("audio_call", "Audio Call"),
                    ("video_call", "Video Call"),
                    ("custom", "Custom Service"),
                    ("community_post", "Community Post"),
                    ("group_chat", "Group Chat"),
                    ("group_audio_call", "Group Audio Call"),
                    ("group_video_call", "Group Video Call"),
                ],
                help_text="Type of service offered",
                max_length=20,
            ),
        ),
    ]
