# Generated by Django 5.2.3 on 2025-07-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="impression_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
