# Generated by Django 5.2.3 on 2025-07-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_poll_impression_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="impression_count",
            new_name="impressions_count",
        ),
    ]
