# Generated by Django 5.2.3 on 2025-07-03 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_rename_impression_count_poll_impressions_count"),
        ("profile", "0003_pseudonymousprofile_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollTextAggregate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text_value", models.CharField(max_length=50)),
                ("response_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-response_count", "text_value"],
            },
        ),
        migrations.CreateModel(
            name="PollTextResponse",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text_value", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="poll",
            name="correct_ranking_order",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="correct_text_answer",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="has_correct_answer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="poll",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="poll_images/"),
        ),
        migrations.AddField(
            model_name="polloption",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="poll",
            name="poll_type",
            field=models.CharField(
                choices=[
                    ("single", "Single Choice"),
                    ("multiple", "Multiple Choice"),
                    ("ranking", "Ranking Poll"),
                    ("text_input", "Text Input Poll"),
                ],
                default="single",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="polloption",
            index=models.Index(
                fields=["poll", "is_correct"], name="polls_pollo_poll_id_b31e77_idx"
            ),
        ),
        migrations.AddField(
            model_name="polltextaggregate",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_aggregates",
                to="polls.poll",
            ),
        ),
        migrations.AddField(
            model_name="polltextresponse",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_responses",
                to="polls.poll",
            ),
        ),
        migrations.AddField(
            model_name="polltextresponse",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_responses",
                to="profile.pseudonymousprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="polltextaggregate",
            index=models.Index(
                fields=["poll", "-response_count"],
                name="polls_pollt_poll_id_55597c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="polltextaggregate",
            index=models.Index(
                fields=["poll", "text_value"], name="polls_pollt_poll_id_3e80c9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="polltextaggregate",
            unique_together={("poll", "text_value")},
        ),
        migrations.AddIndex(
            model_name="polltextresponse",
            index=models.Index(
                fields=["poll", "text_value"], name="polls_pollt_poll_id_f4fd23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="polltextresponse",
            index=models.Index(
                fields=["poll", "profile"], name="polls_pollt_poll_id_936674_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="polltextresponse",
            index=models.Index(
                fields=["profile", "-created_at"], name="polls_pollt_profile_99b547_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="polltextresponse",
            unique_together={("poll", "profile")},
        ),
    ]
