# Generated by Django 5.2.3 on 2025-07-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0003_community_rules"),
        ("polls", "0004_polltextaggregate_polltextresponse_and_more"),
        ("profile", "0003_pseudonymousprofile_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="moderation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="poll",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_moderation", "Pending Moderation"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                ],
                default="pending_moderation",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["status", "community", "-created_at"],
                name="polls_poll_status_5e706a_idx",
            ),
        ),
    ]
