# Generated by Django 5.2.3 on 2025-07-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_poll_moderated_at_poll_moderation_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="explanation",
            field=models.TextField(blank=True),
        ),
    ]
