# Generated by Django 5.2.3 on 2025-07-21 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_poll_explanation"),
        ("profile", "0003_pseudonymousprofile_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollTodo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=200)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todos",
                        to="polls.poll",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_todos",
                        to="profile.pseudonymousprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["is_completed", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["poll", "-created_at"],
                        name="polls_pollt_poll_id_e4669d_idx",
                    ),
                    models.Index(
                        fields=["profile", "-created_at"],
                        name="polls_pollt_profile_8d4222_idx",
                    ),
                ],
            },
        ),
    ]
