# Generated by Django 5.2.3 on 2025-07-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_polltodo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="title",
            field=models.CharField(),
        ),
    ]
