# Generated by Django 5.2.3 on 2025-07-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_alter_poll_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="polltodo",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
