# Generated by Django 5.2.3 on 2025-07-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0005_alter_communitymembership_role"),
        ("polls", "0009_polltodo_is_deleted"),
        ("profile", "0003_pseudonymousprofile_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier for the poll",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="unique_id",
            field=models.CharField(
                blank=True,
                help_text="11-character unique identifier for the poll",
                max_length=11,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["unique_id"], name="polls_poll_unique__0b60c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(fields=["slug"], name="polls_poll_slug_3e2bd9_idx"),
        ),
    ]
