# Generated by Django 5.2.3 on 2025-07-27 18:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0005_alter_communitymembership_role"),
        ("polls", "0010_poll_slug_poll_unique_id_and_more"),
        ("profile", "0003_pseudonymousprofile_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuraTransaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("poll_participation", "Poll Participation"),
                            ("poll_correct", "Poll Correct Answer"),
                            ("streak_bonus", "Streak Bonus"),
                            ("admin_adjustment", "Admin Adjustment"),
                            ("community_reward", "Community Reward"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aura_transactions",
                        to="communities.community",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aura_transactions",
                        to="polls.poll",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aura_transactions",
                        to="profile.pseudonymousprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["profile", "-created_at"],
                        name="polls_aurat_profile_8ec7e3_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "-created_at"],
                        name="polls_aurat_transac_ca4cb5_idx",
                    ),
                    models.Index(
                        fields=["poll", "-created_at"],
                        name="polls_aurat_poll_id_d0ef7f_idx",
                    ),
                    models.Index(
                        fields=["community", "-created_at"],
                        name="polls_aurat_communi_0a7cb6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunityStreak",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("max_streak", models.PositiveIntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("streak_start_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_streaks",
                        to="communities.community",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_streaks",
                        to="profile.pseudonymousprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-current_streak"],
                "indexes": [
                    models.Index(
                        fields=["profile", "community"],
                        name="polls_commu_profile_4a8909_idx",
                    ),
                    models.Index(
                        fields=["community", "-current_streak"],
                        name="polls_commu_communi_769e6e_idx",
                    ),
                    models.Index(
                        fields=["community", "-max_streak"],
                        name="polls_commu_communi_692837_idx",
                    ),
                    models.Index(
                        fields=["profile", "-current_streak"],
                        name="polls_commu_profile_6f6db2_idx",
                    ),
                ],
                "unique_together": {("profile", "community")},
            },
        ),
        migrations.CreateModel(
            name="CommunityStreakActivity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("polls_answered", models.PositiveIntegerField(default=0)),
                ("target_met", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak_activities",
                        to="communities.community",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak_activities",
                        to="profile.pseudonymousprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["profile", "community", "date"],
                        name="polls_commu_profile_14f1a6_idx",
                    ),
                    models.Index(
                        fields=["community", "date", "target_met"],
                        name="polls_commu_communi_1b6605_idx",
                    ),
                    models.Index(
                        fields=["profile", "date"],
                        name="polls_commu_profile_0c25b1_idx",
                    ),
                    models.Index(
                        fields=["profile", "community", "-date"],
                        name="polls_commu_profile_13b786_idx",
                    ),
                ],
                "unique_together": {("profile", "community", "date")},
            },
        ),
        migrations.CreateModel(
            name="PollAnswerResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_correct", models.BooleanField()),
                ("aura_earned", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_results",
                        to="polls.poll",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_answer_results",
                        to="profile.pseudonymousprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["profile", "-created_at"],
                        name="polls_polla_profile_3160d4_idx",
                    ),
                    models.Index(
                        fields=["poll", "is_correct"],
                        name="polls_polla_poll_id_eaf0ac_idx",
                    ),
                    models.Index(
                        fields=["profile", "is_correct", "-created_at"],
                        name="polls_polla_profile_9b14ed_idx",
                    ),
                    models.Index(
                        fields=["profile", "poll"],
                        name="polls_polla_profile_9c71d3_idx",
                    ),
                ],
                "unique_together": {("poll", "profile")},
            },
        ),
    ]
