# Generated by Django 5.2.3 on 2025-07-29 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0014_polllist_prerequisites"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="poll_list",
            field=models.ForeignKey(
                blank=True,
                help_text="List this poll belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll_list",
                to="polls.polllist",
            ),
        ),
        migrations.DeleteModel(
            name="PollListItem",
        ),
    ]
