# Generated by Django 5.2.3 on 2025-07-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture for the user. Optional.",
                null=True,
                upload_to="avatars/",
            ),
        ),
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Banner image for the profile. Optional.",
                null=True,
                upload_to="banners/",
            ),
        ),
    ]
