# Generated by Django 5.2.3 on 2025-07-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_pseudonymousprofile_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="Short bio or description for the profile. Optional.",
                null=True,
            ),
        ),
    ]
