# Generated by Django 5.2.3 on 2025-07-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_pseudonymousprofile_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="total_aura",
            field=models.IntegerField(default=0),
        ),
    ]
