# Generated by Django 5.2.3 on 2025-08-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0004_pseudonymousprofile_total_aura"),
    ]

    operations = [
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="is_online",
            field=models.BooleanField(
                default=False, help_text="Is the user currently online"
            ),
        ),
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="last_seen",
            field=models.DateTimeField(
                blank=True, help_text="Last time the user was seen online", null=True
            ),
        ),
    ]
