# Generated by Django 5.2.3 on 2025-08-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_pseudonymousprofile_is_online_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="total_credits",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="total_earned",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="total_spent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
