# Generated by Django 5.2.3 on 2025-08-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0006_pseudonymousprofile_total_credits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pseudonymousprofile",
            name="total_spent",
        ),
    ]
