# Generated by Django 5.2.3 on 2025-08-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0007_remove_pseudonymousprofile_total_spent"),
    ]

    operations = [
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="headline",
            field=models.CharField(
                blank=True,
                help_text="Short headline or tagline for the profile. Optional.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="instagram",
            field=models.URLField(
                blank=True, help_text="Instagram profile link. Optional.", null=True
            ),
        ),
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="linkedin",
            field=models.URLField(
                blank=True, help_text="LinkedIn profile link. Optional.", null=True
            ),
        ),
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="substack",
            field=models.URLField(
                blank=True, help_text="Substack profile link. Optional.", null=True
            ),
        ),
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="twitter",
            field=models.URLField(
                blank=True, help_text="Twitter profile link. Optional.", null=True
            ),
        ),
        migrations.AddField(
            model_name="pseudonymousprofile",
            name="youtube",
            field=models.URLField(
                blank=True, help_text="YouTube channel link. Optional.", null=True
            ),
        ),
    ]
