# Generated by Django 5.2.3 on 2025-06-30 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericComment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(max_length=1000)),
                ("object_id", models.BigIntegerField()),
                (
                    "anonymous_comment_identifier",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("like_count", models.BigIntegerField(default=0)),
                ("dislike_count", models.BigIntegerField(default=0)),
                ("reply_count", models.BigIntegerField(default=0)),
                ("share_count", models.BigIntegerField(default=0)),
                ("impressions_count", models.BigIntegerField(default=0)),
                ("bookmark_count", models.BigIntegerField(default=0)),
                ("depth", models.SmallIntegerField(default=0)),
                ("is_flagged", models.BooleanField(default=False)),
                ("flag_reason", models.CharField(blank=True, max_length=100)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("requires_moderation", models.BooleanField(default=False)),
                ("community_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "comment_source",
                    models.CharField(
                        choices=[
                            ("post", "Post Comment"),
                            ("community_post", "Community Post Comment"),
                            ("article", "Article Comment"),
                            ("community_article", "Community Article Comment"),
                        ],
                        default="post",
                        max_length=20,
                    ),
                ),
                ("is_taken_down", models.BooleanField(default=False)),
                ("takedown_reason", models.CharField(blank=True, max_length=100)),
                ("takedown_date", models.DateTimeField(blank=True, null=True)),
                ("auto_takedown", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.genericcomment",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="profile.pseudonymousprofile",
                    ),
                ),
                (
                    "takedown_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Profile who took down this comment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="takedown_actions",
                        to="profile.pseudonymousprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-created_at"],
                        name="comments_ge_content_495101_idx",
                    ),
                    models.Index(
                        fields=["parent", "-created_at"],
                        name="comments_ge_parent__c8762b_idx",
                    ),
                    models.Index(
                        fields=["profile", "-created_at"],
                        name="comments_ge_profile_c5ace9_idx",
                    ),
                    models.Index(
                        fields=["is_flagged", "moderation_status"],
                        name="comments_ge_is_flag_0eba34_idx",
                    ),
                    models.Index(
                        fields=["comment_source", "-created_at"],
                        name="comments_ge_comment_c15102_idx",
                    ),
                    models.Index(
                        fields=["community_id", "-created_at"],
                        name="comments_ge_communi_aa9b26_idx",
                    ),
                    models.Index(
                        fields=["is_taken_down"], name="comments_ge_is_take_cfbe2a_idx"
                    ),
                ],
            },
        ),
    ]
