# Generated by Django 5.1.4 on 2025-05-22 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("member", "0013_member_categories"),
        ("profiles", "0005_professionalprofile_completeness_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericComment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(max_length=1000)),
                ("object_id", models.BigIntegerField()),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("public", "Public"),
                            ("pseudonymous", "Pseudonymous"),
                            ("anonymous", "Anonymous"),
                        ],
                        default="public",
                        max_length=15,
                    ),
                ),
                (
                    "anonymous_comment_identifier",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("like_count", models.BigIntegerField(default=0)),
                ("reply_count", models.BigIntegerField(default=0)),
                ("depth", models.SmallIntegerField(default=0)),
                ("allow_link", models.BooleanField(default=True)),
                ("allow_image", models.BooleanField(default=True)),
                ("allow_gif", models.BooleanField(default=True)),
                ("is_flagged", models.BooleanField(default=False)),
                ("flag_reason", models.CharField(blank=True, max_length=100)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("requires_moderation", models.BooleanField(default=False)),
                ("community_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "comment_source",
                    models.CharField(
                        choices=[
                            ("post", "Post Comment"),
                            ("community_post", "Community Post Comment"),
                            ("article", "Article Comment"),
                            ("community_article", "Community Article Comment"),
                        ],
                        default="post",
                        max_length=20,
                    ),
                ),
                ("is_taken_down", models.BooleanField(default=False)),
                ("takedown_reason", models.CharField(blank=True, max_length=100)),
                ("takedown_date", models.DateTimeField(blank=True, null=True)),
                ("auto_takedown", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "anonymous_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="profiles.anonymousprofile",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_comments",
                        to="member.member",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.genericcomment",
                    ),
                ),
                (
                    "professional_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="profiles.professionalprofile",
                    ),
                ),
                (
                    "pseudonymous_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="profiles.pseudonymousprofile",
                    ),
                ),
                (
                    "public_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="profiles.publicprofile",
                    ),
                ),
                (
                    "takedown_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments_taken_down",
                        to="member.member",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-created_at"],
                        name="comments_ge_content_495101_idx",
                    ),
                    models.Index(
                        fields=["parent", "-created_at"],
                        name="comments_ge_parent__c8762b_idx",
                    ),
                    models.Index(
                        fields=["member", "-created_at"],
                        name="comments_ge_member__01a620_idx",
                    ),
                    models.Index(
                        fields=["profile_type", "-created_at"],
                        name="comments_ge_profile_9e5d61_idx",
                    ),
                    models.Index(
                        fields=["professional_profile"],
                        name="comments_ge_profess_de3c20_idx",
                    ),
                    models.Index(
                        fields=["public_profile"], name="comments_ge_public__e92146_idx"
                    ),
                    models.Index(
                        fields=["pseudonymous_profile"],
                        name="comments_ge_pseudon_ab5d9f_idx",
                    ),
                    models.Index(
                        fields=["anonymous_profile"],
                        name="comments_ge_anonymo_653231_idx",
                    ),
                    models.Index(
                        fields=["anonymous_comment_identifier"],
                        name="comments_ge_anonymo_79c841_idx",
                    ),
                    models.Index(
                        fields=["is_flagged", "moderation_status"],
                        name="comments_ge_is_flag_0eba34_idx",
                    ),
                    models.Index(
                        fields=["comment_source", "-created_at"],
                        name="comments_ge_comment_c15102_idx",
                    ),
                    models.Index(
                        fields=["community_id", "-created_at"],
                        name="comments_ge_communi_aa9b26_idx",
                    ),
                    models.Index(
                        fields=["is_taken_down"], name="comments_ge_is_take_cfbe2a_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("anonymous_profile__isnull", True),
                                ("professional_profile__isnull", False),
                                ("profile_type", "professional"),
                                ("pseudonymous_profile__isnull", True),
                                ("public_profile__isnull", True),
                            ),
                            models.Q(
                                ("anonymous_profile__isnull", True),
                                ("professional_profile__isnull", True),
                                ("profile_type", "public"),
                                ("pseudonymous_profile__isnull", True),
                                ("public_profile__isnull", False),
                            ),
                            models.Q(
                                ("anonymous_profile__isnull", True),
                                ("professional_profile__isnull", True),
                                ("profile_type", "pseudonymous"),
                                ("pseudonymous_profile__isnull", False),
                                ("public_profile__isnull", True),
                            ),
                            models.Q(
                                ("anonymous_profile__isnull", False),
                                ("professional_profile__isnull", True),
                                ("profile_type", "anonymous"),
                                ("pseudonymous_profile__isnull", True),
                                ("public_profile__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="comment_has_exactly_one_profile_type",
                    )
                ],
            },
        ),
    ]
