# Generated by Django 5.1.4 on 2025-05-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="genericcomment",
            name="comments_ge_member__01a620_idx",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="member",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="takedown_by",
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="takedown_by_profile_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID of the moderator profile who took down this comment",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="takedown_by_profile_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("professional", "Professional"),
                    ("public", "Public"),
                    ("pseudonymous", "Pseudonymous"),
                    ("anonymous", "Anonymous"),
                ],
                help_text="Profile type of the moderator who took down this comment",
                max_length=15,
                null=True,
            ),
        ),
    ]
