# Generated by Django 5.1.4 on 2025-06-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comments",
            "0002_remove_genericcomment_comments_ge_member__01a620_idx_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="genericcomment",
            name="comment_has_exactly_one_profile_type",
        ),
        migrations.RemoveIndex(
            model_name="genericcomment",
            name="comments_ge_profess_de3c20_idx",
        ),
        migrations.RemoveIndex(
            model_name="genericcomment",
            name="comments_ge_public__e92146_idx",
        ),
        migrations.RemoveIndex(
            model_name="genericcomment",
            name="comments_ge_pseudon_ab5d9f_idx",
        ),
        migrations.RemoveIndex(
            model_name="genericcomment",
            name="comments_ge_anonymo_653231_idx",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="allow_gif",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="allow_image",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="allow_link",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="anonymous_profile",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="professional_profile",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="pseudonymous_profile",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="public_profile",
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="profile_id",
            field=models.BigIntegerField(
                default=1, help_text="ID of the profile based on profile_type"
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="genericcomment",
            index=models.Index(
                fields=["profile_type", "profile_id"],
                name="comments_ge_profile_b96da6_idx",
            ),
        ),
    ]
