# Generated by Django 5.1.4 on 2025-06-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comments",
            "0003_remove_genericcomment_comment_has_exactly_one_profile_type_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="genericcomment",
            name="comments_ge_profile_9e5d61_idx",
        ),
        migrations.RemoveIndex(
            model_name="genericcomment",
            name="comments_ge_anonymo_79c841_idx",
        ),
        migrations.RemoveIndex(
            model_name="genericcomment",
            name="comments_ge_is_flag_0eba34_idx",
        ),
        migrations.RemoveIndex(
            model_name="genericcomment",
            name="comments_ge_comment_c15102_idx",
        ),
        migrations.RemoveIndex(
            model_name="genericcomment",
            name="comments_ge_communi_aa9b26_idx",
        ),
        migrations.RemoveIndex(
            model_name="genericcomment",
            name="comments_ge_is_take_cfbe2a_idx",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="auto_takedown",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="community_id",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="flag_reason",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="like_count",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="requires_moderation",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="takedown_by_profile_id",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="takedown_by_profile_type",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="takedown_date",
        ),
        migrations.RemoveField(
            model_name="genericcomment",
            name="takedown_reason",
        ),
        migrations.AlterField(
            model_name="genericcomment",
            name="comment_source",
            field=models.CharField(default="post", max_length=20),
        ),
        migrations.AlterField(
            model_name="genericcomment",
            name="profile_id",
            field=models.BigIntegerField(),
        ),
        migrations.AddIndex(
            model_name="genericcomment",
            index=models.Index(
                fields=["is_deleted", "is_taken_down", "moderation_status"],
                name="comments_ge_is_dele_bd092b_idx",
            ),
        ),
    ]
