# Generated by Django 5.1.4 on 2025-06-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comments",
            "0004_remove_genericcomment_comments_ge_profile_9e5d61_idx_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="genericcomment",
            name="comments_ge_is_dele_bd092b_idx",
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="auto_takedown",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="community_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="flag_reason",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="like_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="requires_moderation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="takedown_by_profile_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID of the moderator profile who took down this comment",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="takedown_by_profile_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("professional", "Professional"),
                    ("public", "Public"),
                    ("pseudonymous", "Pseudonymous"),
                    ("anonymous", "Anonymous"),
                ],
                help_text="Profile type of the moderator who took down this comment",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="takedown_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="takedown_reason",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="genericcomment",
            name="comment_source",
            field=models.CharField(
                choices=[
                    ("post", "Post Comment"),
                    ("community_post", "Community Post Comment"),
                    ("article", "Article Comment"),
                    ("community_article", "Community Article Comment"),
                ],
                default="post",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="genericcomment",
            name="profile_id",
            field=models.BigIntegerField(
                help_text="ID of the profile based on profile_type"
            ),
        ),
        migrations.AddIndex(
            model_name="genericcomment",
            index=models.Index(
                fields=["profile_type", "-created_at"],
                name="comments_ge_profile_9e5d61_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="genericcomment",
            index=models.Index(
                fields=["anonymous_comment_identifier"],
                name="comments_ge_anonymo_79c841_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="genericcomment",
            index=models.Index(
                fields=["is_flagged", "moderation_status"],
                name="comments_ge_is_flag_0eba34_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="genericcomment",
            index=models.Index(
                fields=["comment_source", "-created_at"],
                name="comments_ge_comment_c15102_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="genericcomment",
            index=models.Index(
                fields=["community_id", "-created_at"],
                name="comments_ge_communi_aa9b26_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="genericcomment",
            index=models.Index(
                fields=["is_taken_down"], name="comments_ge_is_take_cfbe2a_idx"
            ),
        ),
    ]
