# Generated by Django 5.1.4 on 2025-06-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comments",
            "0005_remove_genericcomment_comments_ge_is_dele_bd092b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericcomment",
            name="profile_type",
            field=models.CharField(
                choices=[("public", "Public"), ("anonymous", "Anonymous")],
                default="public",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="genericcomment",
            name="takedown_by_profile_type",
            field=models.CharField(
                blank=True,
                choices=[("public", "Public"), ("anonymous", "Anonymous")],
                help_text="Profile type of the moderator who took down this comment",
                max_length=15,
                null=True,
            ),
        ),
    ]
