# Generated by Django 5.1.4 on 2025-06-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0006_alter_genericcomment_profile_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericcomment",
            name="dislike_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
