# Generated by Django 5.1.4 on 2025-06-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0007_genericcomment_dislike_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericcomment",
            name="bookmark_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="impressions_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="share_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
